### ISSUE TITLE
Support for Braintree Merchant Accounts

### ISSUE THREAD

**Issue by patrickml** [CyCoreSystems/meteor-braintree#2]
Currently this package is missing support for creating a merchant account, the link for the BT docs can be found here https://developers.braintreepayments.com/javascript+node/reference/request/merchant-account/create. I will be working on this as well as updating to the latest release of BT.

**Comment by Ulexus** [comment]
Interesting; I didn't know the API gave access to merchant account creation.  I'd be happy to get PRs for those things.

**Comment by patrickml** [comment]
Yeh I decided to create a new package to keep the API the same as Braintree and easily adapt to any new changes they may make. 

http://atmospherejs.com/patrickml/braintree

if you'd like I can still create a PR for the changes for your package as well.

**Comment by Ulexus** [comment]
Yours looks like a better wrapper concept, anyway.   I'll just direct
people there instead.

**Comment by patrickml** [comment]
Okay cool,

Id love to keep support going for the Meteor Community
